### ISSUE TITLE
Implement all required CRUDs in trump

### ISSUE THREAD

**Issue by gmile** [Nebo15/trump.api#6]
The task includes:

- [x] management of users (done in #1 ),
- [x] management of tokens (done in #11),
- [x] management of clients (done in #12),
- [x] management of apps (app is a join table between user and a client; [screenshot](https://cloud.githubusercontent.com/assets/207112/24724478/903959f2-1a4b-11e7-871b-bed963d448a3.png)).

All of the above must be generated via phoenix generators and look the identical.
